<!--
commet
-->

graph TD

0[use ./lib-dfmmetadata/snippetsCopy/mmd.json see readme]
A[create graph with temporary name like graph.mmd]
B[save to local ./create_resources__media_items/graph.mmd]
C[compete drawing & close file]
D[generate string to use in F.metadata.from.string.image.R]
E[run with parameter]
F[metadata file-s will be created in folder where graph.mmd]
G[graph.mmd was renamad accourding to parameters of function]

0 --> A
A --> B
B --> C
C --> D
D --> E
E --> F
F --> G

